### ISSUE TITLE
Run `npm install` after it has been cloned

### ISSUE THREAD

**Issue by xtuc** [rustwasm/rust-webpack-template#12]
We could run `npm install` for the user after the installation: https://github.com/rustwasm/rust-webpack-template/blob/master/.bin/create-rust-webpack.js#L12.

**Comment by sendilkumarn** [comment]
This means that we have to support both `npm` and `yarn` here. Eventhough it is small. I would like to keep this minimum. WDYT?

**Comment by xtuc** [comment]
We can spawn a shell with `yarn install || npm install`, or just npm. Note that yarn is bundled with some new Nodejs versions.

**Comment by xtuc** [comment]
I just noticed that we don't use yarn, we can only spawn npm.

**Comment by sendilkumarn** [comment]
We don't use `yarn` but what if folks use 🤔 Okay I am creating a PR
