### ISSUE TITLE
Published NPM package is stale

### ISSUE THREAD

**Issue by montag** [rustwasm/rust-webpack-template#123]
### Describe the Bug
Since the NPM package release is still at 1.15 from Oct, I'm not getting the fix from #75 (Nov) and it's swallowing an underlying error. Any chance a new version can get publish?

**Comment by xtuc** [comment]
@fitzgen could you please publish a new version?

**Comment by fitzgen** [comment]
Published! I also added you as an owner @xtuc :)

**Comment by xtuc** [comment]
Great, thanks!
