### ISSUE TITLE
Running `npm init rust-webpack my-app` yields an unexpected result

### ISSUE THREAD

**Issue by kraenhansen** [rustwasm/rust-webpack-template#148]
### Describe the Bug

Running `npm init` with `rust-webpack` yields a directory which is not what I expected.

### Steps to Reproduce

1. Run `npm init rust-webpack my-app`
2. List directory `ls -la my-app`
3. Notice that this is not the template directory as expected.

### Expected Behavior

When I init from `rust-webpack` I expect the newly created directory to have the contents of the [`template`](https://github.com/rustwasm/rust-webpack-template/tree/master/template) directory.

### Actual Behavior

Running the `npm init` command with rust-webpack

    npm init rust-webpack my-app

gives me the following `my-app` directory

```
drwxr-xr-x  13 kraenhansen  staff    416 19 Jun 16:27 .
drwxr-xr-x  77 kraenhansen  staff   2464 19 Jun 16:27 ..
drwxr-xr-x   3 kraenhansen  staff     96 19 Jun 16:27 .bin
drwxr-xr-x  12 kraenhansen  staff    384 19 Jun 16:27 .git
-rw-r--r--   1 kraenhansen  staff     82 19 Jun 16:27 .gitignore
-rw-r--r--   1 kraenhansen  staff    314 19 Jun 16:27 .travis.yml
-rw-r--r--   1 kraenhansen  staff  10847 19 Jun 16:27 LICENSE-APACHE
-rw-r--r--   1 kraenhansen  staff   1071 19 Jun 16:27 LICENSE-MIT
-rw-r--r--   1 kraenhansen  staff   1849 19 Jun 16:27 README.md
drwxr-xr-x  19 kraenhansen  staff    608 19 Jun 16:27 node_modules
-rw-r--r--   1 kraenhansen  staff   4410 19 Jun 16:27 package-lock.json
-rw-r--r--   1 kraenhansen  staff    362 19 Jun 16:27 package.json
drwxr-xr-x  11 kraenhansen  staff    352 19 Jun 16:27 template
```

### Additional Context

As a comparison, calling `npm init` with `react-app` yields a directory with only the files needed to build an app (try running `npm init react-app my-react-app`).

I believe this is happening because https://github.com/rustwasm/rust-webpack-template/pull/144 changes the structure of the repository and a release has not been made quickly thereafter. It would be awesome if this got released very soon as it's super confusing for a newcomer.

**Comment by LukeSugiura** [comment]
Indeed, I'm a newcomer and got super confused.

For newcomers like me, you can work around this by running this code until the new version gets released.
```
npx github:rustwasm/rust-webpack-template my-app
```

**Comment by fitzgen** [comment]
Published a new version and this should be fixed! Thanks for filing an issue!

**Comment by kraenhansen** [comment]
@fitzgen did you test this? I am getting the following error now:

```
npm init rust-webpack my-app
npx: installed 18 in 4.057s
/Users/kraenhansen/.npm/_npx/34260/lib/node_modules/create-rust-webpack/.bin/create-rust-webpack.js:17
    throw new Error("Bad error code when running `" + cmd + " " + args.join(" ") + "`: " + output.status);
    ^

Error: Bad error code when running `git clone --no-tags --depth 1 https://github.com/rustwasm/rust-webpack-template.git my-app/git-clone`: 129
    at run (/Users/kraenhansen/.npm/_npx/34260/lib/node_modules/create-rust-webpack/.bin/create-rust-webpack.js:17:11)
    at Object.<anonymous> (/Users/kraenhansen/.npm/_npx/34260/lib/node_modules/create-rust-webpack/.bin/create-rust-webpack.js:33:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

When I manually run the `git clone --no-tags --depth 1 https://github.com/rustwasm/rust-webpack-template.git my-app/git-clone` command in my terminal I get:

```
error: unknown option `no-tags'
```

I have git version `2.13.1` on a Mac. While I see that this might be slightly outdated it could be good if the tool didn't make assumptions on the features of Git - perhaps did a version check and threw a better error?

I think a better alternative is to fetch the archive from GitHub (using https://github.com/rustwasm/rust-webpack-template/archive/master.zip) instead of using Git to clone the repository .. and to prevent the original issue from happening again, perhaps the tool could fetch the version tag instead of the master branch. Makes sense?

**Comment by Pauan** [comment]
@kraenhansen Git 2.13.1 was released on Jun 5, 2017, that's over 2 years ago. You *really* should upgrade, not just for features, but also for performance and security improvements.

I agree that fetching a tarball would be better, but that'll require some changes.

**Comment by kraenhansen** [comment]
@Pauan I did and that fixed the problem. But again - for an average newcomer, that would not be an obvious next action from the terminal output.
