### ISSUE TITLE
Validate whether if Git is installed in advance

### ISSUE THREAD

**Issue by jamesgeorge007** [rustwasm/rust-webpack-template#154]
### Motivation
The utility assumes `git` is already installed and fails miserably if that is not the case (throws an error). 

### Proposed Solution
IMO, it is good to validate the respective case upfront and warn appropriately.

### Alternatives
N/A

### Additional Context
N/A

**Comment by sendilkumarn** [comment]
Hi @jamesgeorge007 would you be interested to submit a PR?

**Comment by jamesgeorge007** [comment]
yeah, sure :+1:
