### ISSUE TITLE
Fails on supplying unknown options

### ISSUE THREAD

**Issue by jamesgeorge007** [rustwasm/rust-webpack-template#156]
### Describe the Bug

It fails miserably when an unknown option is supplied (we're not depending on any sort of argument parser libraries).

### Steps to Reproduce

`create-rust-webpack -i` (random flag supplied)

### Expected Behavior

An appropriate warning message such that no flags are expected. (The respective case should be validated apppropriately.)

### Actual Behavior

![Screenshot from 2019-08-25 12-31-10](https://user-images.githubusercontent.com/25279263/63646685-43b9fd00-c734-11e9-8ae8-29fb1ad44138.png)

### Additional Context

N/A

**Comment by sendilkumarn** [comment]
@jamesgeorge007 I would prefer it not to use any argument parsing libraries or any libraries per se. 

I will not consider it as a bug. But may be an error handling here might be useful. WDYT?

**Comment by jamesgeorge007** [comment]
yeah, I would happily submit a PR :+1:

**Comment by sendilkumarn** [comment]
Sure thanks then go for it
