### ISSUE TITLE
Why the asyncronous import style that doesn't match the docs

### ISSUE THREAD

**Issue by drewctate** [rustwasm/rust-webpack-template#158]
### Summary

This repository uses the `import()` function instead of the `import` statement like all the documentation the readme links to [for example](https://rustwasm.github.io/docs/wasm-pack/tutorials/npm-browser-packages/using-your-library.html).

Why was the traditional import syntax I see in the tutorials and the deprecated version of the repository abandoned? Is it simply because wasm files are loaded async? If so, how did it work before?

Thanks in advance. I'm just beginning to get my feet wet.

**Comment by Pauan** [comment]
Webpack requires the dynamic `import()`. This will be fixed in the future, but for now it is necessary.

That documentation page is outdated.

**Comment by drewctate** [comment]
Thanks.
