### ISSUE TITLE
Using rust webpack in library form fails

### ISSUE THREAD

**Issue by KMarshland** [rustwasm/rust-webpack-template#167]
### Describe the Bug

Using Rust/WASM creates multiple build files by necessity, as WASM requires dynamic imports to work. However, when trying to consume a library that does so, it cannot find the wasm file.

### Setup

Let's call the library foo-library. foo-library has a number of files, one of which uses a dynamic import of pkg/index.js. When I use webpack to build the release version, it properly builds bundle.js (corresponding to my main library code), bundle.0.js (corresponding to pkg/index.js, presumably), and [hash].module.wasm.

I then having a client calling the equivalent of `import Foo from 'foo-library';`. It loads bundle.js correctly. However, when it makes XHR requests for bundle.0.js and [hash].module.wasm, those requests fail.

### Expected Behavior

I would like to be able to call `import Foo from 'foo-library';` and load the rust/wasm code correctly. 

It seems plausible that there's a webpack configuration option I haven't found yet that allows linking multiple files from a single import in the library. While a fix in the consumer of the library would be more than welcome, it would be ideal if there were a way to make this work in the library itself -- thus the issue in this repository.

### Actual Behavior

Fails to load rust/wasm code.

### Additional Context

I took a look at https://github.com/webpack/webpack/tree/master/examples/multi-part-library, but that doesn't handle the case of one chunk calling another, rather than multiple chunks being called by the client.

**Comment by Pauan** [comment]
@KMarshland You shouldn't be using Webpack to create libraries, it is intended for applications only.

If you want to create a library, you should use [this](https://github.com/rustwasm/wasm-pack-template) instead.

Your library is supposed to just provide the raw ES6 modules and `.wasm` file, and the *consumer* is supposed to use Webpack to bundle everything together.
