### ISSUE TITLE
Set up CI for this template

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/rust-webpack-template#20]
CI should

* run the local version of the template (not 100% sure how to do this with `npm init` and local packages)
* verify that it builds afterwards (`npm run build`)

am I missing anything else it should do?

**Comment by fitzgen** [comment]
For reference, here is the (very simple) `create-wasm-app` CI config: https://github.com/rustwasm/create-wasm-app/blob/master/.travis.yml

**Comment by sendilkumarn** [comment]
waiting for `wasm-pack build command`
