### ISSUE TITLE
`npm init rust-webpack my-app` will install to the current directory

### ISSUE THREAD

**Issue by nikgraf** [rustwasm/rust-webpack-template#22]
The expected behavior would be to install it to create the my-app directory and install it inside there.

**Comment by nikgraf** [comment]
@sendilkumarn I suggest to then in the README change it to:

```
mkdir my-app
cd my-app
npm init rust-webpack
```

What do you think?

**Comment by sendilkumarn** [comment]
well `npm init rust-webpack my-app` does that right?

**Comment by nikgraf** [comment]
That's exactly what I'm trying to say: this doesn't work. Please try the command in your terminal and you will see it will just install the template in the current directory.

**Comment by sendilkumarn** [comment]
Nope, it installs in the directory specified. Can you please check? 

What is the OS, you are using?

**Comment by nikgraf** [comment]
OS: OSX 10.13.6
node v10.9.0 (npm v6.2.0)

![rust-wasm-template 2018-10-01 11_16_59](https://user-images.githubusercontent.com/223045/46280206-95c9c100-c56b-11e8-9bfa-19c10d71cc6e.gif)

**Comment by sendilkumarn** [comment]
From the `log` it seems that you are using the old version of the library.

Can you please try updating the library?

**Comment by nikgraf** [comment]
@sendilkumarn how can I upgrade running  `npm init` or what do you mean?

**Comment by sendilkumarn** [comment]
@fitzgen Can we release a new version? Please remove `cargo.lock` in the new version. It causes issue. 


@nikgraf I am re-opening this, please try to use the new version and let us know if you have the same error. 

Can you also share us more info? like the `create-rust-webpack.js` from your installation ? It will be inside the global node_modules folder.

**Comment by sendilkumarn** [comment]
> Can you please try updating the library?

`npm  i -g create-rust-webpack`

**Comment by fitzgen** [comment]
Published.

**Comment by sendilkumarn** [comment]
Thanks @fitzgen 

@nikgraf it should be working now without any problem. Please try it inside a new directory.
