### ISSUE TITLE
build hangs forever

### ISSUE THREAD

**Issue by saolsen** [rustwasm/rust-webpack-template#65]
I'm using a fresh clone of this projet from today. When I run `npm run build` the build seems to complete but the npm command never finishes and just hangs forever.

**Comment by fitzgen** [comment]
Hi @saolsen, are you running into the same issue as #62 with something about `importedNames`?

If not, can you provide detailed steps to reproduce and console output? Thanks.

**Comment by MaxBittker** [comment]
I'm getting this  too @saolsen

**Comment by MaxBittker** [comment]
however my setup has many of my own modifications so I can't be sure if the problem is my own or in wasm-pack-plugin. just chiming in because I found this issue while debugging

**Comment by xtuc** [comment]
Have you tried to compile the crate yourself? run `cargo build` in the `crate` folder.

**Comment by MaxBittker** [comment]
good question, that part terminates successfully, it's the webpack part that doesn't

**Comment by xtuc** [comment]
One thing that come to my mind is that we used to keep watching even for a one time build, maybe that's what you are observing. IRC we released a fix already but i'm not sure. maybe cc @sendilkumarn?

**Comment by MaxBittker** [comment]
you're right, it does appear to be watching for changes to the crate. I'll double check i'm on the latest version later.

**Comment by MaxBittker** [comment]
it's fixed! I had an old binary! :100:
